# Generated by Django 3.2.7 on 2021-09-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='favourite',
        ),
    ]
