# Generated by Django 3.2.7 on 2021-09-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_rename_likes_post_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='favourite',
            new_name='likes',
        ),
    ]
