# Generated by Django 3.2.7 on 2021-09-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_auto_20210930_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='username',
            new_name='name',
        ),
    ]
