# Generated by Django 3.2.7 on 2022-06-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0016_rename_username_feedback_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='post',
        ),
    ]
